auto: true

markdown: kramdown
input: GFM
highlighter: rouge

gems: [jekyll-paginate]
permalink: none
paginate: 8
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

title: WangJane's blog
url: http://wangjane1030.github.io/
feed: /atom.xml
author_info: <a href="http://wangjane1030.github.io/">WangJane</a>
