auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: WangJane's blog
url: http://wangjane1030.github.io
feed: /atom.xml
author_info: <a href="http://wangjane1030.github.io/">WangJane</a>
